//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace Pes_Tests.LearningServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyProgramming", Namespace="http://schemas.datacontract.org/2004/07/Pes.Core")]
    public partial class StudyProgramming : Pes_Tests.LearningServices.EntityBaseOfStudyProgramming6JTOatw_P {
        
        private string DescriptionField;
        
        private int ProgrammingIDField;
        
        private string ProgrammingNameField;
        
        private Pes_Tests.LearningServices.Binary TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgrammingID {
            get {
                return this.ProgrammingIDField;
            }
            set {
                if ((this.ProgrammingIDField.Equals(value) != true)) {
                    this.ProgrammingIDField = value;
                    this.RaisePropertyChanged("ProgrammingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgrammingName {
            get {
                return this.ProgrammingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgrammingNameField, value) != true)) {
                    this.ProgrammingNameField = value;
                    this.RaisePropertyChanged("ProgrammingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pes_Tests.LearningServices.Binary Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/SubSonic.BaseClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.EntityBaseOfStudyLevel6JTOatw_P))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.StudyLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.EntityBaseOfStudyProgramming6JTOatw_P))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.StudyProgramming))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.Binary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel>))]
    public partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBaseOfStudyLevel6JTOatw_P", Namespace="http://schemas.datacontract.org/2004/07/SubSonic.BaseClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.StudyLevel))]
    public partial class EntityBaseOfStudyLevel6JTOatw_P : Pes_Tests.LearningServices.EntityBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyLevel", Namespace="http://schemas.datacontract.org/2004/07/Pes.Core")]
    public partial class StudyLevel : Pes_Tests.LearningServices.EntityBaseOfStudyLevel6JTOatw_P {
        
        private string DescriptionField;
        
        private int StudyLevelIDField;
        
        private string StudyLevelNameField;
        
        private Pes_Tests.LearningServices.Binary TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudyLevelID {
            get {
                return this.StudyLevelIDField;
            }
            set {
                if ((this.StudyLevelIDField.Equals(value) != true)) {
                    this.StudyLevelIDField = value;
                    this.RaisePropertyChanged("StudyLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyLevelName {
            get {
                return this.StudyLevelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudyLevelNameField, value) != true)) {
                    this.StudyLevelNameField = value;
                    this.RaisePropertyChanged("StudyLevelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pes_Tests.LearningServices.Binary Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBaseOfStudyProgramming6JTOatw_P", Namespace="http://schemas.datacontract.org/2004/07/SubSonic.BaseClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pes_Tests.LearningServices.StudyProgramming))]
    public partial class EntityBaseOfStudyProgramming6JTOatw_P : Pes_Tests.LearningServices.EntityBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    public partial class Binary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] BytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LearningServices.ILearningServices")]
    public interface ILearningServices {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILearningServices/StudyingProgrammingGetAll", ReplyAction="http://tempuri.org/ILearningServices/StudyingProgrammingGetAllResponse")]
        System.IAsyncResult BeginStudyingProgrammingGetAll(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> EndStudyingProgrammingGetAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILearningServices/StudyingLevelGet", ReplyAction="http://tempuri.org/ILearningServices/StudyingLevelGetResponse")]
        System.IAsyncResult BeginStudyingLevelGet(int studyProgrameID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> EndStudyingLevelGet(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILearningServicesChannel : Pes_Tests.LearningServices.ILearningServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StudyingProgrammingGetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StudyingProgrammingGetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class StudyingLevelGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StudyingLevelGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LearningServicesClient : System.ServiceModel.ClientBase<Pes_Tests.LearningServices.ILearningServices>, Pes_Tests.LearningServices.ILearningServices {
        
        private BeginOperationDelegate onBeginStudyingProgrammingGetAllDelegate;
        
        private EndOperationDelegate onEndStudyingProgrammingGetAllDelegate;
        
        private System.Threading.SendOrPostCallback onStudyingProgrammingGetAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginStudyingLevelGetDelegate;
        
        private EndOperationDelegate onEndStudyingLevelGetDelegate;
        
        private System.Threading.SendOrPostCallback onStudyingLevelGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LearningServicesClient() {
        }
        
        public LearningServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LearningServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LearningServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<StudyingProgrammingGetAllCompletedEventArgs> StudyingProgrammingGetAllCompleted;
        
        public event System.EventHandler<StudyingLevelGetCompletedEventArgs> StudyingLevelGetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Pes_Tests.LearningServices.ILearningServices.BeginStudyingProgrammingGetAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStudyingProgrammingGetAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> Pes_Tests.LearningServices.ILearningServices.EndStudyingProgrammingGetAll(System.IAsyncResult result) {
            return base.Channel.EndStudyingProgrammingGetAll(result);
        }
        
        private System.IAsyncResult OnBeginStudyingProgrammingGetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Pes_Tests.LearningServices.ILearningServices)(this)).BeginStudyingProgrammingGetAll(callback, asyncState);
        }
        
        private object[] OnEndStudyingProgrammingGetAll(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> retVal = ((Pes_Tests.LearningServices.ILearningServices)(this)).EndStudyingProgrammingGetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStudyingProgrammingGetAllCompleted(object state) {
            if ((this.StudyingProgrammingGetAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StudyingProgrammingGetAllCompleted(this, new StudyingProgrammingGetAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StudyingProgrammingGetAllAsync() {
            this.StudyingProgrammingGetAllAsync(null);
        }
        
        public void StudyingProgrammingGetAllAsync(object userState) {
            if ((this.onBeginStudyingProgrammingGetAllDelegate == null)) {
                this.onBeginStudyingProgrammingGetAllDelegate = new BeginOperationDelegate(this.OnBeginStudyingProgrammingGetAll);
            }
            if ((this.onEndStudyingProgrammingGetAllDelegate == null)) {
                this.onEndStudyingProgrammingGetAllDelegate = new EndOperationDelegate(this.OnEndStudyingProgrammingGetAll);
            }
            if ((this.onStudyingProgrammingGetAllCompletedDelegate == null)) {
                this.onStudyingProgrammingGetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStudyingProgrammingGetAllCompleted);
            }
            base.InvokeAsync(this.onBeginStudyingProgrammingGetAllDelegate, null, this.onEndStudyingProgrammingGetAllDelegate, this.onStudyingProgrammingGetAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Pes_Tests.LearningServices.ILearningServices.BeginStudyingLevelGet(int studyProgrameID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStudyingLevelGet(studyProgrameID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> Pes_Tests.LearningServices.ILearningServices.EndStudyingLevelGet(System.IAsyncResult result) {
            return base.Channel.EndStudyingLevelGet(result);
        }
        
        private System.IAsyncResult OnBeginStudyingLevelGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int studyProgrameID = ((int)(inValues[0]));
            return ((Pes_Tests.LearningServices.ILearningServices)(this)).BeginStudyingLevelGet(studyProgrameID, callback, asyncState);
        }
        
        private object[] OnEndStudyingLevelGet(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> retVal = ((Pes_Tests.LearningServices.ILearningServices)(this)).EndStudyingLevelGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStudyingLevelGetCompleted(object state) {
            if ((this.StudyingLevelGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StudyingLevelGetCompleted(this, new StudyingLevelGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StudyingLevelGetAsync(int studyProgrameID) {
            this.StudyingLevelGetAsync(studyProgrameID, null);
        }
        
        public void StudyingLevelGetAsync(int studyProgrameID, object userState) {
            if ((this.onBeginStudyingLevelGetDelegate == null)) {
                this.onBeginStudyingLevelGetDelegate = new BeginOperationDelegate(this.OnBeginStudyingLevelGet);
            }
            if ((this.onEndStudyingLevelGetDelegate == null)) {
                this.onEndStudyingLevelGetDelegate = new EndOperationDelegate(this.OnEndStudyingLevelGet);
            }
            if ((this.onStudyingLevelGetCompletedDelegate == null)) {
                this.onStudyingLevelGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStudyingLevelGetCompleted);
            }
            base.InvokeAsync(this.onBeginStudyingLevelGetDelegate, new object[] {
                        studyProgrameID}, this.onEndStudyingLevelGetDelegate, this.onStudyingLevelGetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Pes_Tests.LearningServices.ILearningServices CreateChannel() {
            return new LearningServicesClientChannel(this);
        }
        
        private class LearningServicesClientChannel : ChannelBase<Pes_Tests.LearningServices.ILearningServices>, Pes_Tests.LearningServices.ILearningServices {
            
            public LearningServicesClientChannel(System.ServiceModel.ClientBase<Pes_Tests.LearningServices.ILearningServices> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginStudyingProgrammingGetAll(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("StudyingProgrammingGetAll", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> EndStudyingProgrammingGetAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming> _result = ((System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyProgramming>)(base.EndInvoke("StudyingProgrammingGetAll", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginStudyingLevelGet(int studyProgrameID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = studyProgrameID;
                System.IAsyncResult _result = base.BeginInvoke("StudyingLevelGet", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> EndStudyingLevelGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel> _result = ((System.Collections.ObjectModel.ObservableCollection<Pes_Tests.LearningServices.StudyLevel>)(base.EndInvoke("StudyingLevelGet", _args, result)));
                return _result;
            }
        }
    }
}
